version: "3.9"
services:
  mainapp:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: mainapp/dealscsv
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
