# Generated by Django 3.2.5 on 2021-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='Логин покупателя')),
                ('item', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('total', models.PositiveBigIntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, шт')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
            ],
        ),
    ]
